name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: debian-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Run Tests
      run: |
        echo "Running tests...complete!"
