name: "Terraform Plan"

on:
    pull_request:

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: "us-east-1"

jobs:
    terraform:
        name: Terraform Plan
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout
          uses: actions/checkout@v3
        
